
[[material]]
=== material

[small]#Rfr: link:++http://www.assimp.org/lib_html/structai_material.html++[aiMaterial].#

NOTE: All these functions return _nil_ if the given property is not defined for the material.

* _name_ = *:name*( ) +

* _boolean_ = *:twosided*( ) +

* <<shadingmode, _shadingmode_>> = *:shading*( ) +

* _boolean_ = *:wireframe*( ) +

* <<blendmode, _blendmode_>> = *:blend*( ) +

* _number_ = *:opacity*( ) +
_number_ = *:bumpscaling*( ) +
_number_ = *:shininess*( ) +
_number_ = *:shinpercent*( ) +
_number_ = *:reflectivity*( ) +
_number_ = *:refraction*( ) +

* _r_, _g_, _b_, _a_ = *:color_ambient*( ) +
_r_, _g_, _b_, _a_ = *:color_diffuse*( ) +
_r_, _g_, _b_, _a_ = *:color_emissive*( ) +
_r_, _g_, _b_, _a_ = *:color_reflective*( ) +
_r_, _g_, _b_, _a_ = *:color_specular*( ) +
_r_, _g_, _b_, _a_ = *:color_transparent*( ) +

* _string_ = *:global_bg_image*( ) +


'''

[[material.texture_count]]
* _n_ = *:texture_count*(<<texturetype, _texturetype_>>) +
[small]#Returns the number of textures of the given type.#

The following methods refer to the i-th texture of the given texture type,
where _i_ must be in the range 1 .. <<material.texture_count, texture_count>>(&nbsp;).

* _string_ = *:texture_path*(<<texturetype, _texturetype_>>, _i_)

* _channel_ = *:texture_channel*(<<texturetype, _texturetype_>>, _i_)

* <<textureop, _op_>> = *:texture_op*(<<texturetype, _texturetype_>>, _i_)

* <<texturemapping, _mapping_>> = *:texture_mapping*(<<texturetype, _texturetype_>>, _i_)

* _number_ = *:texture_blend*(<<texturetype, _texturetype_>>, _i_)

* <<texturemapmode, _mapmode_u_>>, <<texturemapmode, _mapmode_v_>> 
= *:texture_mapmode*(<<texturetype, _texturetype_>>, _i_)

* _x_, _y_, _z_ = *:texture_axis*(<<texturetype, _texturetype_>>, _i_)

* _x_, _y_ = *:texture_translation*(<<texturetype, _texturetype_>>, _i_)

* _x_, _y_ = *:texture_scaling*(<<texturetype, _texturetype_>>, _i_)

* _radians_ = *:texture_rotation*(<<texturetype, _texturetype_>>, _i_)

* <<textureflags, _textureflags_>> = *:texture_flags*(<<texturetype, _texturetype_>>, _i_)

'''

The following functions provide a more compact way to retrieve the material textures.

* _counts_ =*:all_texture_counts*( ) +
[small]#Returns a table with the counts for all <<texturetype, _texturetype_>>s
(e.g. _counts.diffuse_ = 2 if there are 2 '_diffuse_' textures).#

* _textures_ =*:all_textures*([<<texturetype, _texturetype_>>]) +
[small]#Returns a table with the properties of all the material textures. +
If the optional _texturetype_ parameter is given, only the textures of that type are listed. +
Each entry of the table describes a texture, and has the following format
(optional fields have a _nil_ value when not defined for the texture): +
*_textures[i]_* = { +
_type_: <<texturetype, texturetype>>, +
_flags_: <<textureflags, textureflags>>, +
_path_: string, +
_channel_: integer (1-based, opt.), +
_op_: <<textureop, _textureop_>> (opt.), +
_mapping_: <<texturemapping, _texturemapping_>> (opt.), +
_blend_: number (opt.), +
_mapmode_u_: <<texturemapmode, _texturemapmode_>> (opt.), +
_mapmode_v_: <<texturemapmode, _texturemapmode_>> (opt.), +
_axis_: {number, number, number} (opt.), +
_translation_: {number, number} (opt.), +
_scaling_: {number, number} (opt.), +
_rotation_: number (radians, opt.), +
}.#

